stages:
- deploy

# 安装依赖
install_deps:
  stage: install_deps
  only:
    - develop
    - master
  script:
    - cnpm install
    - bower install --allow-root
# 运行代码检测
lint:
  stage: lint
  only:
    - develop
  script:
    - gulp jshint
# 运行测试用例
test:
  stage: test
  only:
    - develop
  script:
    - npm run unit-test
# 编译
build:
  stage: build
  only:
    - develop
  script:
    - gulp build


