image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - mvn clean install
  only:
    - develop
  tags:
    - dev

job_test:
  stage: test
  script:
    - mvn test
  tags:
    - dev

job_deploy:
  stage: deploy
  script:
    - echo "deploy over..."
  tags:
    - dev