spring:
  application:
    name: bechatwallet
  cloud:
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    name: bechatwallet
    #        url: jdbc:mysql://39.105.26.249:3306/PMBC
    #        url: jdbc:mysql://172.17.0.1:3306/wallet
    #url: jdbc:mysql://39.105.26.249:3306/vahwallet?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/vahwallet?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    #password: 68d63351097d882f
    # 阿里巴巴druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: pro.bechat.wallet

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    pro.bechat.wallet.domain.dao: DEBUG

#绑定IP servert.host IP
server:
  context-path: /bechatwallet
  port: 8090
  address: 192.168.10.119
  tomcat:
    uri-encoding: UTF-8

#配置第三方访问路径
yellowduck:
  url: "http://39.105.26.249:9090"
#  url: "http://127.0.0.1:9090"
#  url: "http://192.168.10.103:9090"