spring:
  application:
    name: bechatwallet
  cloud:
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  datasource:
        name: VAHWallet
#        url: jdbc:mysql://39.105.26.249:3306/PMBC
#        url: jdbc:mysql://172.17.0.1:3306/wallet
        url: jdbc:mysql://103.65.180.165:3306/VAHWallet
        username: VAHWallet
        password: WxfTaZTFe7h6ZhCy
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: pro.bechat.wallet

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    pro.bechat.wallet.domain.dao: DEBUG

#配置servert.host暴露IP
server:
      context-path: /bechatwallet
      port: 8080

