spring:
  application:
    name: information
  activemq:
    broker-url: failover:(tcp://192.168.38.32:61616)?jms.prefetchPolicy.queuePrefetch=1&timeout=30000
    in-memory: true
    pool:
      enabled: true
    
  aop:
    auto: true
    proxy-target-class: true

com:
  travelsky:
    ypb:
      core-pool-size: 10
      queue-capacity: 8
      max-pool-size: 30
      mq-executor: Ypb-Messages-MQ-Executor_
      keep-alive: 60
