package pro.bechat.wallet.domain.dao;

import org.springframework.stereotype.Repository;
import pro.bechat.wallet.domain.model.model.Contract;

@Repository
public interface ContractMapper extends BasicMapper<Contract>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long contractid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    int insert(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    Contract selectByPrimaryKey(Long contractid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Contract record);
}