package pro.bechat.wallet.domain.dao;


import org.springframework.stereotype.Repository;
import pro.bechat.wallet.domain.model.model.Wallet;

@Repository
public interface WalletMapper extends BasicMapper<Wallet>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    Wallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Wallet record);


    Wallet exist(String address);

}