package pro.bechat.wallet.domain.model.model;

import java.io.Serializable;

public class Contract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.contractId
     *
     * @mbggenerated
     */
    private Long contractid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.contractAddr
     *
     * @mbggenerated
     */
    private String contractaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.transactionAddr
     *
     * @mbggenerated
     */
    private String transactionaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.tokenName
     *
     * @mbggenerated
     */
    private String tokenname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.tokenSymbol
     *
     * @mbggenerated
     */
    private String tokensymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.initialSupply
     *
     * @mbggenerated
     */
    private Long initialsupply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.gas
     *
     * @mbggenerated
     */
    private Long gas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.gasPrice
     *
     * @mbggenerated
     */
    private Long gasprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.formAddr
     *
     * @mbggenerated
     */
    private String formaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_CONTRACT.updateTime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.contractId
     *
     * @return the value of WLT_T_CONTRACT.contractId
     *
     * @mbggenerated
     */
    public Long getContractid() {
        return contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.contractId
     *
     * @param contractid the value for WLT_T_CONTRACT.contractId
     *
     * @mbggenerated
     */
    public void setContractid(Long contractid) {
        this.contractid = contractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.contractAddr
     *
     * @return the value of WLT_T_CONTRACT.contractAddr
     *
     * @mbggenerated
     */
    public String getContractaddr() {
        return contractaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.contractAddr
     *
     * @param contractaddr the value for WLT_T_CONTRACT.contractAddr
     *
     * @mbggenerated
     */
    public void setContractaddr(String contractaddr) {
        this.contractaddr = contractaddr == null ? null : contractaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.transactionAddr
     *
     * @return the value of WLT_T_CONTRACT.transactionAddr
     *
     * @mbggenerated
     */
    public String getTransactionaddr() {
        return transactionaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.transactionAddr
     *
     * @param transactionaddr the value for WLT_T_CONTRACT.transactionAddr
     *
     * @mbggenerated
     */
    public void setTransactionaddr(String transactionaddr) {
        this.transactionaddr = transactionaddr == null ? null : transactionaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.tokenName
     *
     * @return the value of WLT_T_CONTRACT.tokenName
     *
     * @mbggenerated
     */
    public String getTokenname() {
        return tokenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.tokenName
     *
     * @param tokenname the value for WLT_T_CONTRACT.tokenName
     *
     * @mbggenerated
     */
    public void setTokenname(String tokenname) {
        this.tokenname = tokenname == null ? null : tokenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.tokenSymbol
     *
     * @return the value of WLT_T_CONTRACT.tokenSymbol
     *
     * @mbggenerated
     */
    public String getTokensymbol() {
        return tokensymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.tokenSymbol
     *
     * @param tokensymbol the value for WLT_T_CONTRACT.tokenSymbol
     *
     * @mbggenerated
     */
    public void setTokensymbol(String tokensymbol) {
        this.tokensymbol = tokensymbol == null ? null : tokensymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.initialSupply
     *
     * @return the value of WLT_T_CONTRACT.initialSupply
     *
     * @mbggenerated
     */
    public Long getInitialsupply() {
        return initialsupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.initialSupply
     *
     * @param initialsupply the value for WLT_T_CONTRACT.initialSupply
     *
     * @mbggenerated
     */
    public void setInitialsupply(Long initialsupply) {
        this.initialsupply = initialsupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.gas
     *
     * @return the value of WLT_T_CONTRACT.gas
     *
     * @mbggenerated
     */
    public Long getGas() {
        return gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.gas
     *
     * @param gas the value for WLT_T_CONTRACT.gas
     *
     * @mbggenerated
     */
    public void setGas(Long gas) {
        this.gas = gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.gasPrice
     *
     * @return the value of WLT_T_CONTRACT.gasPrice
     *
     * @mbggenerated
     */
    public Long getGasprice() {
        return gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.gasPrice
     *
     * @param gasprice the value for WLT_T_CONTRACT.gasPrice
     *
     * @mbggenerated
     */
    public void setGasprice(Long gasprice) {
        this.gasprice = gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.userId
     *
     * @return the value of WLT_T_CONTRACT.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.userId
     *
     * @param userid the value for WLT_T_CONTRACT.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.formAddr
     *
     * @return the value of WLT_T_CONTRACT.formAddr
     *
     * @mbggenerated
     */
    public String getFormaddr() {
        return formaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.formAddr
     *
     * @param formaddr the value for WLT_T_CONTRACT.formAddr
     *
     * @mbggenerated
     */
    public void setFormaddr(String formaddr) {
        this.formaddr = formaddr == null ? null : formaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.status
     *
     * @return the value of WLT_T_CONTRACT.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.status
     *
     * @param status the value for WLT_T_CONTRACT.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.createTime
     *
     * @return the value of WLT_T_CONTRACT.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.createTime
     *
     * @param createtime the value for WLT_T_CONTRACT.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_CONTRACT.updateTime
     *
     * @return the value of WLT_T_CONTRACT.updateTime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_CONTRACT.updateTime
     *
     * @param updatetime the value for WLT_T_CONTRACT.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Contract other = (Contract) that;
        return (this.getContractid() == null ? other.getContractid() == null : this.getContractid().equals(other.getContractid()))
            && (this.getContractaddr() == null ? other.getContractaddr() == null : this.getContractaddr().equals(other.getContractaddr()))
            && (this.getTransactionaddr() == null ? other.getTransactionaddr() == null : this.getTransactionaddr().equals(other.getTransactionaddr()))
            && (this.getTokenname() == null ? other.getTokenname() == null : this.getTokenname().equals(other.getTokenname()))
            && (this.getTokensymbol() == null ? other.getTokensymbol() == null : this.getTokensymbol().equals(other.getTokensymbol()))
            && (this.getInitialsupply() == null ? other.getInitialsupply() == null : this.getInitialsupply().equals(other.getInitialsupply()))
            && (this.getGas() == null ? other.getGas() == null : this.getGas().equals(other.getGas()))
            && (this.getGasprice() == null ? other.getGasprice() == null : this.getGasprice().equals(other.getGasprice()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getFormaddr() == null ? other.getFormaddr() == null : this.getFormaddr().equals(other.getFormaddr()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatetime() == null ? other.getUpdatetime() == null : this.getUpdatetime().equals(other.getUpdatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getContractid() == null) ? 0 : getContractid().hashCode());
        result = prime * result + ((getContractaddr() == null) ? 0 : getContractaddr().hashCode());
        result = prime * result + ((getTransactionaddr() == null) ? 0 : getTransactionaddr().hashCode());
        result = prime * result + ((getTokenname() == null) ? 0 : getTokenname().hashCode());
        result = prime * result + ((getTokensymbol() == null) ? 0 : getTokensymbol().hashCode());
        result = prime * result + ((getInitialsupply() == null) ? 0 : getInitialsupply().hashCode());
        result = prime * result + ((getGas() == null) ? 0 : getGas().hashCode());
        result = prime * result + ((getGasprice() == null) ? 0 : getGasprice().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getFormaddr() == null) ? 0 : getFormaddr().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatetime() == null) ? 0 : getUpdatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_CONTRACT
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", contractid=").append(contractid);
        sb.append(", contractaddr=").append(contractaddr);
        sb.append(", transactionaddr=").append(transactionaddr);
        sb.append(", tokenname=").append(tokenname);
        sb.append(", tokensymbol=").append(tokensymbol);
        sb.append(", initialsupply=").append(initialsupply);
        sb.append(", gas=").append(gas);
        sb.append(", gasprice=").append(gasprice);
        sb.append(", userid=").append(userid);
        sb.append(", formaddr=").append(formaddr);
        sb.append(", status=").append(status);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}