package pro.bechat.wallet.domain.model.model;

import java.io.Serializable;

public class TransactionRecord  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.transactionTime
     *
     * @mbggenerated
     */
    private String transactiontime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.fromUser
     *
     * @mbggenerated
     */
    private String fromuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.toUser
     *
     * @mbggenerated
     */
    private String touser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.fromAddress
     *
     * @mbggenerated
     */
    private String fromaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.toAddress
     *
     * @mbggenerated
     */
    private String toaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.transactionId
     *
     * @mbggenerated
     */
    private String transactionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.coinType
     *
     * @mbggenerated
     */
    private String cointype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.gasPrice
     *
     * @mbggenerated
     */
    private String gasprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.confirm
     *
     * @mbggenerated
     */
    private String confirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.blockHash
     *
     * @mbggenerated
     */
    private String blockhash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.blockNumber
     *
     * @mbggenerated
     */
    private String blocknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.contractAddress
     *
     * @mbggenerated
     */
    private String contractaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.cumulativeGasUsed
     *
     * @mbggenerated
     */
    private String cumulativegasused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.gasUsed
     *
     * @mbggenerated
     */
    private String gasused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.logs
     *
     * @mbggenerated
     */
    private String logs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.logsBloom
     *
     * @mbggenerated
     */
    private String logsbloom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.transactionHash
     *
     * @mbggenerated
     */
    private String transactionhash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_TRANSACTIONRECORD.transactionIndex
     *
     * @mbggenerated
     */
    private String transactionindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_T_TRANSACTIONRECORD
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.fromUser
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.fromUser
     *
     * @mbggenerated
     */
    public String getFromuser() {
        return fromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.fromUser
     *
     * @param fromuser the value for WLT_T_TRANSACTIONRECORD.fromUser
     *
     * @mbggenerated
     */
    public void setFromuser(String fromuser) {
        this.fromuser = fromuser == null ? null : fromuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.toUser
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.toUser
     *
     * @mbggenerated
     */
    public String getTouser() {
        return touser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.toUser
     *
     * @param touser the value for WLT_T_TRANSACTIONRECORD.toUser
     *
     * @mbggenerated
     */
    public void setTouser(String touser) {
        this.touser = touser == null ? null : touser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.fromAddress
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.fromAddress
     *
     * @mbggenerated
     */
    public String getFromaddress() {
        return fromaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.fromAddress
     *
     * @param fromaddress the value for WLT_T_TRANSACTIONRECORD.fromAddress
     *
     * @mbggenerated
     */
    public void setFromaddress(String fromaddress) {
        this.fromaddress = fromaddress == null ? null : fromaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.toAddress
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.toAddress
     *
     * @mbggenerated
     */
    public String getToaddress() {
        return toaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.toAddress
     *
     * @param toaddress the value for WLT_T_TRANSACTIONRECORD.toAddress
     *
     * @mbggenerated
     */
    public void setToaddress(String toaddress) {
        this.toaddress = toaddress == null ? null : toaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.transactionId
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.transactionId
     *
     * @mbggenerated
     */
    public String getTransactionid() {
        return transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.transactionId
     *
     * @param transactionid the value for WLT_T_TRANSACTIONRECORD.transactionId
     *
     * @mbggenerated
     */
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid == null ? null : transactionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.coinType
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.coinType
     *
     * @mbggenerated
     */
    public String getCointype() {
        return cointype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.coinType
     *
     * @param cointype the value for WLT_T_TRANSACTIONRECORD.coinType
     *
     * @mbggenerated
     */
    public void setCointype(String cointype) {
        this.cointype = cointype == null ? null : cointype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.amount
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.amount
     *
     * @param amount the value for WLT_T_TRANSACTIONRECORD.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.gasPrice
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.gasPrice
     *
     * @mbggenerated
     */
    public String getGasprice() {
        return gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.gasPrice
     *
     * @param gasprice the value for WLT_T_TRANSACTIONRECORD.gasPrice
     *
     * @mbggenerated
     */
    public void setGasprice(String gasprice) {
        this.gasprice = gasprice == null ? null : gasprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.confirm
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.confirm
     *
     * @mbggenerated
     */
    public String getConfirm() {
        return confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.confirm
     *
     * @param confirm the value for WLT_T_TRANSACTIONRECORD.confirm
     *
     * @mbggenerated
     */
    public void setConfirm(String confirm) {
        this.confirm = confirm == null ? null : confirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.blockHash
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.blockHash
     *
     * @mbggenerated
     */
    public String getBlockhash() {
        return blockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.blockHash
     *
     * @param blockhash the value for WLT_T_TRANSACTIONRECORD.blockHash
     *
     * @mbggenerated
     */
    public void setBlockhash(String blockhash) {
        this.blockhash = blockhash == null ? null : blockhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.blockNumber
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.blockNumber
     *
     * @mbggenerated
     */
    public String getBlocknumber() {
        return blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.blockNumber
     *
     * @param blocknumber the value for WLT_T_TRANSACTIONRECORD.blockNumber
     *
     * @mbggenerated
     */
    public void setBlocknumber(String blocknumber) {
        this.blocknumber = blocknumber == null ? null : blocknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.contractAddress
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.contractAddress
     *
     * @mbggenerated
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.contractAddress
     *
     * @param contractaddress the value for WLT_T_TRANSACTIONRECORD.contractAddress
     *
     * @mbggenerated
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress == null ? null : contractaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.cumulativeGasUsed
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.cumulativeGasUsed
     *
     * @mbggenerated
     */
    public String getCumulativegasused() {
        return cumulativegasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.cumulativeGasUsed
     *
     * @param cumulativegasused the value for WLT_T_TRANSACTIONRECORD.cumulativeGasUsed
     *
     * @mbggenerated
     */
    public void setCumulativegasused(String cumulativegasused) {
        this.cumulativegasused = cumulativegasused == null ? null : cumulativegasused.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.gasUsed
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.gasUsed
     *
     * @mbggenerated
     */
    public String getGasused() {
        return gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.gasUsed
     *
     * @param gasused the value for WLT_T_TRANSACTIONRECORD.gasUsed
     *
     * @mbggenerated
     */
    public void setGasused(String gasused) {
        this.gasused = gasused == null ? null : gasused.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.logs
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.logs
     *
     * @mbggenerated
     */
    public String getLogs() {
        return logs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.logs
     *
     * @param logs the value for WLT_T_TRANSACTIONRECORD.logs
     *
     * @mbggenerated
     */
    public void setLogs(String logs) {
        this.logs = logs == null ? null : logs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.logsBloom
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.logsBloom
     *
     * @mbggenerated
     */
    public String getLogsbloom() {
        return logsbloom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.logsBloom
     *
     * @param logsbloom the value for WLT_T_TRANSACTIONRECORD.logsBloom
     *
     * @mbggenerated
     */
    public void setLogsbloom(String logsbloom) {
        this.logsbloom = logsbloom == null ? null : logsbloom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.status
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.status
     *
     * @param status the value for WLT_T_TRANSACTIONRECORD.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.transactionHash
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.transactionHash
     *
     * @mbggenerated
     */
    public String getTransactionhash() {
        return transactionhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.transactionHash
     *
     * @param transactionhash the value for WLT_T_TRANSACTIONRECORD.transactionHash
     *
     * @mbggenerated
     */
    public void setTransactionhash(String transactionhash) {
        this.transactionhash = transactionhash == null ? null : transactionhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_TRANSACTIONRECORD.transactionIndex
     *
     * @return the value of WLT_T_TRANSACTIONRECORD.transactionIndex
     *
     * @mbggenerated
     */
    public String getTransactionindex() {
        return transactionindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_TRANSACTIONRECORD.transactionIndex
     *
     * @param transactionindex the value for WLT_T_TRANSACTIONRECORD.transactionIndex
     *
     * @mbggenerated
     */
    public void setTransactionindex(String transactionindex) {
        this.transactionindex = transactionindex == null ? null : transactionindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_TRANSACTIONRECORD
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TransactionRecord other = (TransactionRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTransactiontime() == null ? other.getTransactiontime() == null : this.getTransactiontime().equals(other.getTransactiontime()))
            && (this.getFromuser() == null ? other.getFromuser() == null : this.getFromuser().equals(other.getFromuser()))
            && (this.getTouser() == null ? other.getTouser() == null : this.getTouser().equals(other.getTouser()))
            && (this.getFromaddress() == null ? other.getFromaddress() == null : this.getFromaddress().equals(other.getFromaddress()))
            && (this.getToaddress() == null ? other.getToaddress() == null : this.getToaddress().equals(other.getToaddress()))
            && (this.getTransactionid() == null ? other.getTransactionid() == null : this.getTransactionid().equals(other.getTransactionid()))
            && (this.getCointype() == null ? other.getCointype() == null : this.getCointype().equals(other.getCointype()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getGasprice() == null ? other.getGasprice() == null : this.getGasprice().equals(other.getGasprice()))
            && (this.getConfirm() == null ? other.getConfirm() == null : this.getConfirm().equals(other.getConfirm()))
            && (this.getBlockhash() == null ? other.getBlockhash() == null : this.getBlockhash().equals(other.getBlockhash()))
            && (this.getBlocknumber() == null ? other.getBlocknumber() == null : this.getBlocknumber().equals(other.getBlocknumber()))
            && (this.getContractaddress() == null ? other.getContractaddress() == null : this.getContractaddress().equals(other.getContractaddress()))
            && (this.getCumulativegasused() == null ? other.getCumulativegasused() == null : this.getCumulativegasused().equals(other.getCumulativegasused()))
            && (this.getGasused() == null ? other.getGasused() == null : this.getGasused().equals(other.getGasused()))
            && (this.getLogs() == null ? other.getLogs() == null : this.getLogs().equals(other.getLogs()))
            && (this.getLogsbloom() == null ? other.getLogsbloom() == null : this.getLogsbloom().equals(other.getLogsbloom()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTransactionhash() == null ? other.getTransactionhash() == null : this.getTransactionhash().equals(other.getTransactionhash()))
            && (this.getTransactionindex() == null ? other.getTransactionindex() == null : this.getTransactionindex().equals(other.getTransactionindex()));
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTransactiontime() {
        return transactiontime;
    }

    public void setTransactiontime(String transactiontime) {
        this.transactiontime = transactiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_TRANSACTIONRECORD
     *
     * @mbggenerated
     */

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTransactiontime() == null) ? 0 : getTransactiontime().hashCode());
        result = prime * result + ((getFromuser() == null) ? 0 : getFromuser().hashCode());
        result = prime * result + ((getTouser() == null) ? 0 : getTouser().hashCode());
        result = prime * result + ((getFromaddress() == null) ? 0 : getFromaddress().hashCode());
        result = prime * result + ((getToaddress() == null) ? 0 : getToaddress().hashCode());
        result = prime * result + ((getTransactionid() == null) ? 0 : getTransactionid().hashCode());
        result = prime * result + ((getCointype() == null) ? 0 : getCointype().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getGasprice() == null) ? 0 : getGasprice().hashCode());
        result = prime * result + ((getConfirm() == null) ? 0 : getConfirm().hashCode());
        result = prime * result + ((getBlockhash() == null) ? 0 : getBlockhash().hashCode());
        result = prime * result + ((getBlocknumber() == null) ? 0 : getBlocknumber().hashCode());
        result = prime * result + ((getContractaddress() == null) ? 0 : getContractaddress().hashCode());
        result = prime * result + ((getCumulativegasused() == null) ? 0 : getCumulativegasused().hashCode());
        result = prime * result + ((getGasused() == null) ? 0 : getGasused().hashCode());
        result = prime * result + ((getLogs() == null) ? 0 : getLogs().hashCode());
        result = prime * result + ((getLogsbloom() == null) ? 0 : getLogsbloom().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTransactionhash() == null) ? 0 : getTransactionhash().hashCode());
        result = prime * result + ((getTransactionindex() == null) ? 0 : getTransactionindex().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_TRANSACTIONRECORD
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fromuser=").append(fromuser);
        sb.append(", touser=").append(touser);
        sb.append(", fromaddress=").append(fromaddress);
        sb.append(", toaddress=").append(toaddress);
        sb.append(", transactionid=").append(transactionid);
        sb.append(", cointype=").append(cointype);
        sb.append(", amount=").append(amount);
        sb.append(", gasprice=").append(gasprice);
        sb.append(", confirm=").append(confirm);
        sb.append(", blockhash=").append(blockhash);
        sb.append(", blocknumber=").append(blocknumber);
        sb.append(", contractaddress=").append(contractaddress);
        sb.append(", cumulativegasused=").append(cumulativegasused);
        sb.append(", gasused=").append(gasused);
        sb.append(", logs=").append(logs);
        sb.append(", logsbloom=").append(logsbloom);
        sb.append(", status=").append(status);
        sb.append(", transactionhash=").append(transactionhash);
        sb.append(", transactionindex=").append(transactionindex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}