package pro.bechat.wallet.domain.model.model;

import java.io.Serializable;

public class Wallet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.privateKey
     *
     * @mbggenerated
     */
    private String privatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.walletType
     *
     * @mbggenerated
     */
    private String wallettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.walletName
     *
     * @mbggenerated
     */
    private String walletname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.updateTme
     *
     * @mbggenerated
     */
    private String updatetme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WLT_T_WALLET.walletImg
     *
     * @mbggenerated
     */
    private String walletimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.id
     *
     * @return the value of WLT_T_WALLET.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.id
     *
     * @param id the value for WLT_T_WALLET.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.address
     *
     * @return the value of WLT_T_WALLET.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.address
     *
     * @param address the value for WLT_T_WALLET.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.privateKey
     *
     * @return the value of WLT_T_WALLET.privateKey
     *
     * @mbggenerated
     */
    public String getPrivatekey() {
        return privatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.privateKey
     *
     * @param privatekey the value for WLT_T_WALLET.privateKey
     *
     * @mbggenerated
     */
    public void setPrivatekey(String privatekey) {
        this.privatekey = privatekey == null ? null : privatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.walletType
     *
     * @return the value of WLT_T_WALLET.walletType
     *
     * @mbggenerated
     */
    public String getWallettype() {
        return wallettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.walletType
     *
     * @param wallettype the value for WLT_T_WALLET.walletType
     *
     * @mbggenerated
     */
    public void setWallettype(String wallettype) {
        this.wallettype = wallettype == null ? null : wallettype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.walletName
     *
     * @return the value of WLT_T_WALLET.walletName
     *
     * @mbggenerated
     */
    public String getWalletname() {
        return walletname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.walletName
     *
     * @param walletname the value for WLT_T_WALLET.walletName
     *
     * @mbggenerated
     */
    public void setWalletname(String walletname) {
        this.walletname = walletname == null ? null : walletname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.userId
     *
     * @return the value of WLT_T_WALLET.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.userId
     *
     * @param userid the value for WLT_T_WALLET.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.createTime
     *
     * @return the value of WLT_T_WALLET.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.createTime
     *
     * @param createtime the value for WLT_T_WALLET.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.updateTme
     *
     * @return the value of WLT_T_WALLET.updateTme
     *
     * @mbggenerated
     */
    public String getUpdatetme() {
        return updatetme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.updateTme
     *
     * @param updatetme the value for WLT_T_WALLET.updateTme
     *
     * @mbggenerated
     */
    public void setUpdatetme(String updatetme) {
        this.updatetme = updatetme == null ? null : updatetme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WLT_T_WALLET.walletImg
     *
     * @return the value of WLT_T_WALLET.walletImg
     *
     * @mbggenerated
     */
    public String getWalletimg() {
        return walletimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WLT_T_WALLET.walletImg
     *
     * @param walletimg the value for WLT_T_WALLET.walletImg
     *
     * @mbggenerated
     */
    public void setWalletimg(String walletimg) {
        this.walletimg = walletimg == null ? null : walletimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Wallet other = (Wallet) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getPrivatekey() == null ? other.getPrivatekey() == null : this.getPrivatekey().equals(other.getPrivatekey()))
            && (this.getWallettype() == null ? other.getWallettype() == null : this.getWallettype().equals(other.getWallettype()))
            && (this.getWalletname() == null ? other.getWalletname() == null : this.getWalletname().equals(other.getWalletname()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getUpdatetme() == null ? other.getUpdatetme() == null : this.getUpdatetme().equals(other.getUpdatetme()))
            && (this.getWalletimg() == null ? other.getWalletimg() == null : this.getWalletimg().equals(other.getWalletimg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getPrivatekey() == null) ? 0 : getPrivatekey().hashCode());
        result = prime * result + ((getWallettype() == null) ? 0 : getWallettype().hashCode());
        result = prime * result + ((getWalletname() == null) ? 0 : getWalletname().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getUpdatetme() == null) ? 0 : getUpdatetme().hashCode());
        result = prime * result + ((getWalletimg() == null) ? 0 : getWalletimg().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WLT_T_WALLET
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", privatekey=").append(privatekey);
        sb.append(", wallettype=").append(wallettype);
        sb.append(", walletname=").append(walletname);
        sb.append(", userid=").append(userid);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetme=").append(updatetme);
        sb.append(", walletimg=").append(walletimg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}