server:
  port: 8082

spring:
  application:
    name: information
  profiles:
      active: dataSourceTest, dataRedisTest, dev
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: true
  aop:
    auto: true
    proxy-target-class: true

activeMq: UME_YPB_QUEUE


